version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes: 
      - ../.project-data/postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=go-clean
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - internal
  go:
    container_name: accounts
    build:
      context: .
    ports:
      - 9000:9000
    environment:
      DB_HOST: localhost
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
networks:
  internal:
    driver: bridge
  