version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ../.project-data/postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=go-clean
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - internal
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=3
    networks:
      - internal
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  go:
    container_name: accounts
    build:
      context: .
    ports:
      - 9000:9000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one
    ports:
      - 14268:14268
      - 16686:16686
networks:
  internal:
    driver: bridge
