CREATE TABLE IF NOT EXISTS rooms (
   id uuid NOT NULL,
   name VARCHAR (128),
   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
   updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
   PRIMARY KEY (id)
);