DB:
  HOST: "postgres"
  USER: "root"
  PASSWORD: "root"
  NAME: "go-clean"
  PORT: "5432"
  SSL: "disable"
Jobs:
  Enabled: false
  Concurrency: 10
  RedisAddress: "localhost:6379"
Telemetry:
  Enabled: true
  Name: "Boilerplate Project"
  JaegerURL: "http://127.0.0.1:14268/api/traces"
  Version: "1"
  Filepath: ""
Logger:
  OutputPath: "/var/log/project/debug.log"
  ErrOutputPath: "/var/log/project/error.log"
  DefaultPath: "/Users/hugorojas/go/src/go-clean/debug.log"
  MaxSize: 300
  MaxBackups: 3
  MaxAge: 15
JWT:
  SECRET: ZTP02X517M4PUND7
  EXPIRATION: 60 
PORT: 9000
SERVER_TIMEOUT: 3
IS_PRODUCTION: false
