DB:
  URL: "postgres://root:root@localhost:5432/go-clean?sslmode=disable"
  HOST: "localhost"
  USER: "root"
  PASSWORD: "root"
  NAME: "go-clean"
  PORT: "5432"
  SSL: "disable"

Telemetry:
  Enabled: true
  Name: "Default Project"
  JaegerURL: http://localhost:16686
  Version: "1"
  Filepath: ""
PORT: 9500
