DB:
  HOST: "localhost"
  USER: "root"
  PASSWORD: "root"
  NAME: "go-clean"
  PORT: "5432"
  SSL: "disable"

Telemetry:
  Enabled: true
  Name: "Boilerplate Project"
  JaegerURL: "http://127.0.0.1:14268/api/traces"
  Version: "1"
  Filepath: ""
JWT:
  SECRET: ZTP02X517M4PUND7
  EXPIRATION: 60 
PORT: 9000
