DB:
  URL: "postgres://root:root@localhost:5432/go-clean?sslmode=disable"
  HOST: "localhost"
  USER: "root"
  PASSWORD: "root"
  NAME: "go-clean"
  PORT: "5432"
  SSL: "disable"

Telemetry:
  Enabled: true
  Name: "Default Project"
  JaegerURL: "http://localhost:14268/api/traces"
  Version: "1"
  Filepath: ""
JWT:
  SECRET: "ZTP02X517M4PUND7"
  EXPIRATION: 60 
PORT: 9000
