name: Test checker
on: [push, pull_request]
jobs:
    build-and-run:
        name: Run linter and test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Go
              uses: actions/setup-go@v3
              with:
                go-version: '1.19'
                check-latest: true
                cache: true
            - name: golangci-lint
              run: go run github.com/golangci/golangci-lint/cmd/golangci-lint run ./...
            - name: Test
              run: go test -json ./internal/... > test.json
            - name: Annotate tests
              if: always()
              uses: guyarb/golang-test-annotations@v0.5.1
              with:
                test-results: test.json
    run-integration-test:
        name: Run integration test
        runs-on: ubuntu-latest
        
        services:
          postgres:
            image: postgres:latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Build app image
          run: docker-compose build app

        - name: Start app and database
          run: docker-compose up -d

        - name: Run integration tests
          run: docker-compose run --rm app go test -cover  -v -race  ./integration/...

        - name: Stop app and database
          run: docker-compose down
